### ISSUE TITLE
Meeting #1

### ISSUE THREAD

**Issue by joaoricardo000** [CheesecakeLabs/django-drf-boilerplate#1]
## Definition of the first boilerplate scope and patterns.  
- django-project-template  
Our boilerplate must be a django project template. [Example](https://github.com/jpadilla/django-project-template)
- Libs for auth/login: [django-allauth](https://github.com/pennersr/django-allauth), [django-rest-auth](https://github.com/Tivix/django-rest-auth), [drf.authtoken](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication)  
Check if rest-auth can be replaced by allauth.
- Readme
Keep a well written readme file, explaining every part of the project
- [API Blueprint](https://apiblueprint.org/) for every endpoint
- Tests for every functionality
- CI / codecov / pyflakes: automate tests and code structure coverage with tools to create metrics.
- Dockerfile / docker-compose: keep all platform well documented as well as easy to build.
- PostgreSQL: convention SQL database

Default folder structure:
```
├── Dockerfile
├── README.md
├── boilerplate
│   ├── auth
│   │   ├── __init__.py
│   │   ├── admin.py
│   │   ├── api
│   │   │   └── v1
│   │   │       ├── permissions.py
│   │   │       ├── serializers.py
│   │   │       ├── urls.py
│   │   │       └── views.py
│   │   ├── apps.py
│   │   ├── migrations
│   │   │   └── __init__.py
│   │   ├── models.py
│   │   └── tests
│   │       └── tests_one.py
│   ├── boilerplate
│   │   ├── __init__.py
│   │   ├── settings.py
│   │   ├── urls.py
│   │   └── wsgi.py
│   └── manage.py
├── docker-compose.yml
└── requirements.txt
```

**Comment by jonatasbaldin** [comment]
Hi everyone!

That's a lot to cover on our first interaction. I'll open PRs for each task, so we don't do the same work!

**Comment by accordeiro** [comment]
One suggestion: why don't we create one (open-source, yay!) auth library of our own, instead of using the listed ones? I'll tell you why:

- Django-allauth is unnecessarily big (and has some very bad design decisions that will leave a footprint in your database even if you decide to ditch it in the long run)
- Django-rest-auth is inconsistent and incomplete (and to make it complete, you'll need to use the lib above)
- [Djoser](https://github.com/sunscrapers/djoser) might be the best option IMO, but still has some extensibiliy issues.

**Comment by jonatasbaldin** [comment]
Hey @accordeiro, we talked about it and it is a thing we want to do, but we thought to first have a stable boilerplate to be used, than create a authentication library 💃
