### ISSUE TITLE
Implement django-rest-auth and drf.authtoken

### ISSUE THREAD

**Issue by jonatasbaldin** [CheesecakeLabs/django-drf-boilerplate#5]
Hi! We should use the package django-rest-auth and use the DRF Auth Token to have endpoints for Token authentication.

- [ ] Implement the package django-rest-auth
- [ ] Document how to use on README.md
- [ ] Document API endpoints
- [ ] Create tests

**Comment by joaoricardo000** [comment]
Spent some time understanding how drf, allauth and rest_auth work together and found out that **rest-auth** requires **allauth**. It is an API implementation of what allauth does by template views.  

[![Django + drf + allauth](https://cloud.githubusercontent.com/assets/2717047/22422991/a5ac733a-e6d6-11e6-9104-3b45245dd179.jpg)](https://docs.google.com/drawings/d/1yVTHL3p3zC3T7Xgu5KV7FlVGZHym0aiP8ZwIZFX_4u4/edit?usp=sharing)  

The red token is created by django-rest-framework.authtoken, the blue group by allauth. The rest is default django.contrib - django-extentions and rest_auth does not add any model.

The default urls of rest_auth and allauth:  

| URL                                                                  | View                                                          | Name                                 |
|----------------------------------------------------------------------|---------------------------------------------------------------|--------------------------------------|
| rest_auth + .registration                                                                                                          |                                      |
| /login/                                                              | rest_auth.views.LoginView                                     | rest_login                           |
| /logout/                                                             | rest_auth.views.LogoutView                                    | rest_logout                          |
| /password/change/                                                    | rest_auth.views.PasswordChangeView                            | rest_password_change                 |
| /password/reset/                                                     | rest_auth.views.PasswordResetView                             | rest_password_reset                  |
| /password/reset/confirm/                                             | rest_auth.views.PasswordResetConfirmView                      | rest_password_reset_confirm          |
| /registration/                                                       | rest_auth.registration.views.RegisterView                     | rest_register                        |
| /registration/account-confirm-email/\<key\>/                           | django.views.generic.base.TemplateView                        | account_confirm_email                |
| /registration/verify-email/                                          | rest_auth.registration.views.VerifyEmailView                  | rest_verify_email                    |
| /user/                                                               | rest_auth.views.UserDetailsView                               | rest_user_details                    |
|                                                                      |                                                               |                                      |
| allauth + .account  .socialaccount .socialaccount.providers.facebook |                                                               |                                      |
| /confirm-email/                                                      | allauth.account.views.EmailVerificationSentView               | account_email_verification_sent      |
| /confirm-email/\<key\>/                                                | allauth.account.views.ConfirmEmailView                        | account_confirm_email                |
| /email/                                                              | allauth.account.views.EmailView                               | account_email                        |
| /facebook/login/                                                     | allauth.socialaccount.providers.oauth2.views.view             | facebook_login                       |
| /facebook/login/callback/                                            | allauth.socialaccount.providers.oauth2.views.view             | facebook_callback                    |
| /facebook/login/token/                                               | allauth.socialaccount.providers.facebook.views.login_by_token | facebook_login_by_token              |
| /inactive/                                                           | allauth.account.views.AccountInactiveView                     | account_inactive                     |
| /login/                                                              | allauth.account.views.LoginView                               | account_login                        |
| /logout/                                                             | allauth.account.views.LogoutView                              | account_logout                       |
| /password/change/                                                    | allauth.account.views.PasswordChangeView                      | account_change_password              |
| /password/reset/                                                     | allauth.account.views.PasswordResetView                       | account_reset_password               |
| /password/reset/done/                                                | allauth.account.views.PasswordResetDoneView                   | account_reset_password_done          |
| /password/reset/key/\<uidb36\>-\<key\>/                                  | allauth.account.views.PasswordResetFromKeyView                | account_reset_password_from_key      |
| /password/reset/key/done/                                            | allauth.account.views.PasswordResetFromKeyDoneView            | account_reset_password_from_key_done |
| /password/set/                                                       | allauth.account.views.PasswordSetView                         | account_set_password                 |
| /signup/                                                             | allauth.account.views.SignupView                              | account_signup                       |
| /social/connections/                                                 | allauth.socialaccount.views.ConnectionsView                   | socialaccount_connections            |
| /social/login/cancelled/                                             | allauth.socialaccount.views.LoginCancelledView                | socialaccount_login_cancelled        |
| /social/login/error/                                                 | allauth.socialaccount.views.LoginErrorView                    | socialaccount_login_error            |
| /social/signup/                                                      | allauth.socialaccount.views.SignupView                        | socialaccount_signup                 |
  
Many functionalities overlap, that's because the rest_auth endpoints work as API (drf), while all_auth are default django form/template rendered views.  
Although this project is about building an API, some template rendered views are quite usefull, for example, the password reset and email confirmation. Both require a deeplink with the app to pass the required token, while a simple html would solve.  
We can also use a custom User model if we need too, without losing any of the django-admin functionalities.
  
My idea of building our own auth project, right now, consists in creating a project using both allauth and rest_auth, but with explicit url definitions and customized classes as examples. We also need a name for it - 'auth' is used by django already.

**Comment by smaniotto** [comment]
This would also cover issue #3 right?

**Comment by joaoricardo000** [comment]
Yes, the first version will have a 'login with facebook' functionality.
